version: '3.0'
services:
  postgres-db:
    image: postgres:15.0
    container_name: postgres_container
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: pasteur
      POSTGRES_PASSWORD: 2292892000
      PGPORT: 5433
    networks:
      - pasteur_network
networks:
  pasteur_network:
    driver: bridge
